name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: php-actions/composer@v6
        with:
          php_version: "8.2"

      - uses: php-actions/phpunit@v3
        with:
          php_extensions: xdebug mbstring
          php_version: "8.2"
          args: --coverage-clover=coverage/clover-coverage.xml
        env:
          XDEBUG_MODE: coverage

      - name: Code Coverage Check
        uses: themichaelhall/check-code-coverage@v2
        if: github.event_name == 'pull_request'
        with:
          report: coverage/clover-coverage.xml
          required-percentage: 80